# Generated by Django 3.2.25 on 2024-04-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nickname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.png', upload_to='profile/')),
            ],
        ),
    ]
